apiVersion: v1
kind: ConfigMap
metadata:
  name: trombiflow-config
  namespace: trombiflow
data:
  ENV: "production"
  PORT: "8000"
  STORAGE_TYPE: "local"
  UPLOAD_DIR: "/data/uploads"
  FRONTEND_PORT: "80"
