apiVersion: v1
kind: ServiceAccount
metadata:
  name: trombiflow
  namespace: trombiflow
  labels:
    app: trombiflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trombiflow
  namespace: trombiflow
  labels:
    app: trombiflow
rules:
  # Permettre la lecture des ConfigMaps et Secrets
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  # Permettre l'accès aux PersistentVolumes
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trombiflow
  namespace: trombiflow
  labels:
    app: trombiflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trombiflow
subjects:
  - kind: ServiceAccount
    name: trombiflow
    namespace: trombiflow
